### PR TITLE
Updated qs dependency to fix snyk vulnerabilities report

### PR DESCRIPTION
**Pull request by eugeniop**
Running snyk:

```
$ snyk test
✗ High severity vulnerability found on qs@4.0.0
- desc: Prototype Override Protection Bypass
- info: https://snyk.io/vuln/npm:qs:20170213
- from: connect-multiparty@2.0.0 > qs@4.0.0
Upgrade direct dependency qs@4.0.0 to qs@6.0.4
```

### CODE REVIEW

**Comment by dougwilson** [comment]
The report only applies when you are using `allowPrototypes: false` feature. Since we don't use that feature, this is not affected.

**Comment by eugeniop** [comment]
ah, cool. thx!

**Comment by josiasmontag** [comment]
@dougwilson Unfortunately, this is not correct. `allowPrototypes` of qs defaults to `false`. So this module uses that "feature". 
This means users can overwrite object prototypes using multipart requests. The qs dependency should be updated! Thanks.

**Comment by dougwilson** [comment]
@josiasmontag it defaults to false _in the version this module uses_.

**Comment by dougwilson** [comment]
@josiasmontag it defaults to true _ in the version this module uses _. Make sure you are looking at the docs and code for qs of the version this this module is actually using, not the current qs version.

**Comment by josiasmontag** [comment]
@dougwilson Okay, then even worse. The current version of this module allows it to override the object prototype using multipart requests. Which is exactly the vulnerability snyk complains about. 
Simple test for this:

```js
var app = connect();

app.use(multipart());

app.use(function (req, res) {
    res.end(JSON.stringify(req.body));
});


it('should not allow to oberwrite the prototype', function (done) {
            request(app)
                .post('/')
                .field(']=toString', 'Tobi')
                .expect(200, '{"]=toString":"Tobi"}', done);
})
```

The server returns `{"Tobi":true}` in this example, which means we have overwritten the prototype.

**Comment by dougwilson** [comment]
There is no issue here. That is how this module works. You are not reading the vulnerability text correctly. The issue is if you are relying on the prototype protection, it doesn't work. We don't rely on that protection at all, so the issue is moot.

**Pull request closed without merging**
